// <auto-generated />
using System;
using HairCutAppAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HairCutAppAPI.Data.Migrations
{
    [DbContext(typeof(HDBContext))]
    [Migration("20211018112727_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HairCutAppAPI.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppointmentDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("ComboId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PromotionalCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RatingId")
                        .HasColumnType("int");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SalonId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.AppointmentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int?>("CrewId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("ComboId");

                    b.HasIndex("CrewId");

                    b.ToTable("AppointmentDetails");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.AppointmentRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("RatingComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("AppointmentRatings");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Combos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Cắt Tóc",
                            Duration = 1,
                            LastUpdated = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Cắt Tóc",
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Cắt Tóc Gội Đầu",
                            Duration = 2,
                            LastUpdated = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Cắt Tóc Gội Đầu",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Cắt Tóc Gội Đầu Rửa Mặt",
                            Duration = 2,
                            LastUpdated = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Cắt Tóc Gội Đầu Rửa Mặt",
                            Status = "active"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Cắt Tóc, Ráy Táy, Gội Đầu, Rửa Mặt, Dắp mặt",
                            Duration = 3,
                            LastUpdated = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Chăm sóc đầy đử",
                            Status = "active"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Cắt Tóc, Ráy Táy",
                            Duration = 1,
                            LastUpdated = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Cắt tóc ráy tai",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.ComboDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ComboDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComboId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            ComboId = 2,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 3,
                            ComboId = 2,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 4,
                            ComboId = 3,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 5,
                            ComboId = 3,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 6,
                            ComboId = 3,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 7,
                            ComboId = 4,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 8,
                            ComboId = 4,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 9,
                            ComboId = 4,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 10,
                            ComboId = 4,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 11,
                            ComboId = 4,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 12,
                            ComboId = 5,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 13,
                            ComboId = 5,
                            ServiceId = 3
                        });
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Crew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.CrewDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CrewId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrewId");

                    b.HasIndex("StaffId");

                    b.ToTable("CrewDetails");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.CustomersCodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomersCodes");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.PromotionalCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUniversal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsesPerCustomer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PromotionalCodes");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Rating")
                        .HasColumnType("bit");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SalonId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Salons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Salon 1",
                            LastUpdate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Salon 1",
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Salon 2",
                            LastUpdate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Salon 2",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Salon 3",
                            LastUpdate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Salon 3",
                            Status = "active"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Salon 4",
                            LastUpdate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Salon 4",
                            Status = "active"
                        });
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.SalonsCodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("SalonId");

                    b.ToTable("SalonsCodes");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Cắt tóc",
                            LastUpdated = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Cắt tóc",
                            Price = 50000m,
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Gội Đầu",
                            LastUpdated = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Gội Đầu",
                            Price = 20000m,
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Ráy tai",
                            LastUpdated = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Ráy tai",
                            Price = 10000m,
                            Status = "active"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Gội Đầu",
                            LastUpdated = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Rửa Mặt",
                            Price = 20000m,
                            Status = "active"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Description = "Đắp Mặt",
                            LastUpdated = new DateTime(2021, 10, 18, 18, 27, 27, 418, DateTimeKind.Local).AddTicks(809),
                            Name = "Đắp Mặt",
                            Price = 20000m,
                            Status = "active"
                        });
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.SlotOfDay", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("SlotsOfDay");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeSpan(0, 7, 30, 0, 0),
                            StartTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            StartTime = new TimeSpan(0, 7, 30, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeSpan(0, 8, 30, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new TimeSpan(0, 9, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 30, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            StartTime = new TimeSpan(0, 11, 30, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            StartTime = new TimeSpan(0, 12, 30, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            EndTime = new TimeSpan(0, 13, 30, 0, 0),
                            StartTime = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 13, 30, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            EndTime = new TimeSpan(0, 14, 30, 0, 0),
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 14, 30, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            EndTime = new TimeSpan(0, 15, 30, 0, 0),
                            StartTime = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 15, 30, 0, 0)
                        },
                        new
                        {
                            Id = 19,
                            EndTime = new TimeSpan(0, 16, 30, 0, 0),
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 20,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 16, 30, 0, 0)
                        },
                        new
                        {
                            Id = 21,
                            EndTime = new TimeSpan(0, 17, 30, 0, 0),
                            StartTime = new TimeSpan(0, 17, 0, 0, 0)
                        },
                        new
                        {
                            Id = 22,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 17, 30, 0, 0)
                        },
                        new
                        {
                            Id = 23,
                            EndTime = new TimeSpan(0, 18, 30, 0, 0),
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 24,
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            StartTime = new TimeSpan(0, 18, 30, 0, 0)
                        },
                        new
                        {
                            Id = 25,
                            EndTime = new TimeSpan(0, 19, 30, 0, 0),
                            StartTime = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            Id = 26,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            StartTime = new TimeSpan(0, 19, 30, 0, 0)
                        },
                        new
                        {
                            Id = 27,
                            EndTime = new TimeSpan(0, 20, 30, 0, 0),
                            StartTime = new TimeSpan(0, 20, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppointmentsNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SalonId")
                        .HasColumnType("int");

                    b.Property<string>("StaffType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SuccessfulAppointmentsNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.HasIndex("UserId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.WorkSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SlotOfDayId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SlotOfDayId");

                    b.HasIndex("StaffId");

                    b.ToTable("WorkSlots");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Appointment", b =>
                {
                    b.HasOne("HairCutAppAPI.Entities.Combo", null)
                        .WithMany("Appointments")
                        .HasForeignKey("ComboId");

                    b.HasOne("HairCutAppAPI.Entities.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairCutAppAPI.Entities.Salon", "Salon")
                        .WithMany("Appointments")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.AppointmentDetail", b =>
                {
                    b.HasOne("HairCutAppAPI.Entities.Appointment", "Appointment")
                        .WithOne("AppointmentDetail")
                        .HasForeignKey("HairCutAppAPI.Entities.AppointmentDetail", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairCutAppAPI.Entities.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairCutAppAPI.Entities.Crew", "Crew")
                        .WithMany()
                        .HasForeignKey("CrewId");

                    b.Navigation("Appointment");

                    b.Navigation("Combo");

                    b.Navigation("Crew");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.AppointmentRating", b =>
                {
                    b.HasOne("HairCutAppAPI.Entities.Appointment", "Appointment")
                        .WithOne("Rating")
                        .HasForeignKey("HairCutAppAPI.Entities.AppointmentRating", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.ComboDetail", b =>
                {
                    b.HasOne("HairCutAppAPI.Entities.Combo", "Combo")
                        .WithMany("ComboDetails")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairCutAppAPI.Entities.Service", "Service")
                        .WithMany("ComboDetails")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.CrewDetail", b =>
                {
                    b.HasOne("HairCutAppAPI.Entities.Crew", "Crew")
                        .WithMany("CrewDetails")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairCutAppAPI.Entities.Staff", "Staff")
                        .WithMany("CrewDetails")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Customer", b =>
                {
                    b.HasOne("HairCutAppAPI.Entities.AppUser", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.CustomersCodes", b =>
                {
                    b.HasOne("HairCutAppAPI.Entities.PromotionalCode", "Code")
                        .WithMany("CustomersCodes")
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairCutAppAPI.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Code");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Device", b =>
                {
                    b.HasOne("HairCutAppAPI.Entities.AppUser", "User")
                        .WithOne("Device")
                        .HasForeignKey("HairCutAppAPI.Entities.Device", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Review", b =>
                {
                    b.HasOne("HairCutAppAPI.Entities.AppUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairCutAppAPI.Entities.Salon", "Salon")
                        .WithMany("Reviews")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.SalonsCodes", b =>
                {
                    b.HasOne("HairCutAppAPI.Entities.PromotionalCode", "Code")
                        .WithMany("SalonsCodes")
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairCutAppAPI.Entities.Salon", "Salon")
                        .WithMany("SalonsCodes")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Code");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Staff", b =>
                {
                    b.HasOne("HairCutAppAPI.Entities.Salon", "Salon")
                        .WithMany("Staffs")
                        .HasForeignKey("SalonId");

                    b.HasOne("HairCutAppAPI.Entities.AppUser", "User")
                        .WithMany("Staffs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.WorkSlot", b =>
                {
                    b.HasOne("HairCutAppAPI.Entities.SlotOfDay", "SlotOfDay")
                        .WithMany("WorkSlots")
                        .HasForeignKey("SlotOfDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairCutAppAPI.Entities.Staff", "Staff")
                        .WithMany("WorkSlots")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlotOfDay");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.AppUser", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Device");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Appointment", b =>
                {
                    b.Navigation("AppointmentDetail");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Combo", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ComboDetails");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Crew", b =>
                {
                    b.Navigation("CrewDetails");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Customer", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.PromotionalCode", b =>
                {
                    b.Navigation("CustomersCodes");

                    b.Navigation("SalonsCodes");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Salon", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Reviews");

                    b.Navigation("SalonsCodes");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Service", b =>
                {
                    b.Navigation("ComboDetails");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.SlotOfDay", b =>
                {
                    b.Navigation("WorkSlots");
                });

            modelBuilder.Entity("HairCutAppAPI.Entities.Staff", b =>
                {
                    b.Navigation("CrewDetails");

                    b.Navigation("WorkSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
